### ISSUE TITLE
Replica load balancer created unexpectedly

### ISSUE THREAD

**Issue by avandras** [zalando-incubator/senza-base-template#6]
As we've learnt today, if you specify `-v "add_replica_loadbalancer=1"` or -v "add_replica_loadbalancer=0"` or -v "add_replica_loadbalancer=123456"` or possibly something else, the replica load balancer is created in every case.  To avoid it, one has to omit this option.

**Comment by alexeyklyukin** [comment]
Should be fixed in fd4c39b75fae29cb3708d4b3dea9b17f0f0d67dd
